services:
  mongodb:
    image: mongo:9.0
    container_name: mongodb-hi1031
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
      - ./mongodb:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: Webshop
      WEBSHOP_PASSWORD: ${WEBSHOP_PASSWORD}

  tomcat:
    image: tomcat:jre25-temurin-jammy
    container_name: tomcat-hi1031
    ports:
      - "8080:8080"
    volumes:
      - ./target/lab1.war:/usr/local/tomcat/webapps/lab1.war
    environment:
      WEBSHOP_PASSWORD: ${WEBSHOP_PASSWORD}
    depends_on:
      - mongodb

volumes:
  mongodb-data:
