version: '3.8'

services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb-hi1031
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

  tomcat:
    image: tomcat:jre25-temurin-jammy
    container_name: tomcat-hi1031
    ports:
      - "8080:8080"
    volumes:
      - (PLACEHOLDER):/usr/local/tomcat/webapps/lab1.war
    depends_on:
      - mongodb

volumes:
  mongodb-data: