version: '3.8'

services:
  mysql:
    image: mysql:8.4
    container_name: mysql-hi1031
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: <placeholder>

  tomcat:
    image: tomcat:jre25-temurin-jammy
    container_name: tomcat-hi1031
    ports:
      - "8080:8080"
    volumes:
      - <placeholder>:/usr/local/tomcat/webapps/lab1.war
    depends_on:
      - mysql

volumes:
  mysql-data: